#Biliotheken, Funktionen

In [ ]:
import numpy as np
import pandas as pd

#Datenladen

In [ ]:
df_calls = pd.read_pickle('Cl_Calls.pkl')
df_cont = pd.read_pickle('Cl_Cont.pkl')
df_spend = pd.read_pickle('Cl_Spend.pkl')
df_deals = pd.read_pickle('2_Deals.pkl')

In [ ]:
df_calls.head(2)

,Id,Call Start Time,Call Owner Name,CONTACTID,Call Type,Call Duration (in seconds),Call Status,Outgoing Call Status,Scheduled in CRM
0,5805028000000805001,2023-06-30 08:43:00,John Doe,NaN,Inbound,171.0,Received,NaN,NaN
1,5805028000000768006,2023-06-30 08:46:00,John Doe,NaN,Outbound,28.0,Attended Dialled,Completed,0.0

In [ ]:
df_cont.head(2)

,Id,Contact Owner Name,Created Time,Modified Time
0,5805028000000645014,Rachel White,2023-06-27 11:28:00,2023-12-22 13:34:00
1,5805028000000872003,Charlie Davis,2023-07-03 11:31:00,2024-05-21 10:23:00

In [ ]:
df_deals.head(2)

,Id,Deal Owner Name,Closing Date,Quality,Stage,Lost Reason,Page,Campaign,Content,Term,...,Close Time,Month,Duration days,Duration hours,Owner Status,longitude,latitude,country,city,federal_state
0,5805028000056864695,Ben Hall,NaT,Unknown,New Lead,Unknown,/eng/test,03.07.23women,v16,women,...,NaT,NaT,NaN,NaN,Stable,NaN,NaN,None,None,None
1,5805028000056859489,Ulysses Adams,NaT,Unknown,New Lead,Unknown,/at-eng,Unknown,Unknown,Unknown,...,NaT,NaT,NaN,NaN,Stable,NaN,NaN,None,None,None

In [ ]:
ua_deals = df_deals['Contact Name'].nunique()
print('ua_deals =', ua_deals)
ua_calls = df_calls['CONTACTID'].nunique()
print('ua_calls =',ua_calls)
ua_conts = df_cont['Id'].nunique()
print('ua_conts =',ua_conts)

ua_deals = 16868
ua_calls = 15214
ua_conts = 18510

Wir nehmen für die Berechnungen den größten Wert UA = 18510.

In [ ]:
ua = ua_conts

In [ ]:
df_filt = df_deals[df_deals['Stage'] == 'Payment Done']

In [ ]:
df_ux_ui = df_filt[df_filt['Product'] == 'UX/UI Design']
df_dig_mark = df_filt[df_filt['Product'] == 'Digital Marketing']
df_web_dev = df_filt[df_filt['Product'] == 'Web Developer']

In [ ]:
b = len(df_filt)
b_dig_mark = len(df_dig_mark)
b_ux_ui = len(df_ux_ui)
b_web_dev = len(df_web_dev)

In [ ]:
c1 = b/ua_conts
c1_dig_mark = b_dig_mark/ua_conts
c1_ux_ui = b_ux_ui/ua_conts
c1_web_dev = b_web_dev/ua_conts

In [ ]:
df_spend.head(2)

,Date,Source,Campaign,Impressions,Spend,Clicks,AdGroup,Ad
0,2023-07-03,Google Ads,gen_analyst_DE,6,0.00,0,Unknown,Unknown
1,2023-07-03,Google Ads,performancemax_eng_DE,4,0.01,1,Unknown,Unknown

In [ ]:
ac = df_spend['Spend'].sum()

In [ ]:
t = df_filt['Months of study'].sum()
t_dig_mark = df_dig_mark['Months of study'].sum()
t_ux_ui = df_ux_ui['Months of study'].sum()
t_web_dev = df_web_dev['Months of study'].sum()

In [ ]:
df_deals['Product'].value_counts()

Product
Unknown              16144
Digital Marketing     1944
UX/UI Design          1004
Web Developer          565
Name: count, dtype: int64

In [ ]:
diff_amount = df_deals['Offer Total Amount'] - df_deals['Initial Amount Paid']
diff_course = df_deals['Course duration'] - 1
diff_mounth = df_deals['Months of study'] - 1
rest_payment = (((diff_amount / diff_course) * diff_mounth) + df_deals['Initial Amount Paid'])

In [ ]:
df_deals['AOV_i'] = np.where(
    (df_deals['Offer Total Amount'] - df_deals['Initial Amount Paid']) > 0,
    rest_payment / df_deals['Months of study'],
    df_deals['Offer Total Amount'] / df_deals['Course duration']
)

df_deals['R_i'] = df_deals['AOV_i'] * df_deals['Months of study']

df_ux_ui = df_deals[df_deals['Product'] == 'UX/UI Design']
df_dig_mark = df_deals[df_deals['Product'] == 'Digital Marketing']
df_web_dev = df_deals[df_deals['Product'] == 'Web Developer']

In [ ]:
revenu = df_deals['R_i'].sum()
revenu

np.float64(3434094.696969697)

In [ ]:
df_deals[df_deals['Months of study'] == 7]

,Id,Deal Owner Name,Closing Date,Quality,Stage,Lost Reason,Page,Campaign,Content,Term,...,Duration days,Duration hours,Owner Status,longitude,latitude,country,city,federal_state,AOV_i,R_i
12291,5805028000023854193,Nina Scott,2024-02-13,C - Low,Payment Done,Unknown,/eng/test,performancemax_digitalmarkt_ru_DE,_{region_name}_,Unknown,...,44.0,1060.400000,Stable,10.465903,51.210656,Germany,Mühlhausen,Thuringia,1000.000000,7000.000000
12325,5805028000023653144,Paula Underwood,2024-01-20,C - Low,Payment Done,Unknown,/direct,Unknown,Unknown,Unknown,...,21.0,515.300000,Stable,13.404954,52.520007,Germany,Berlin,Berlin,360.000000,2520.000000
12327,5805028000023686141,Quincy Vincent,2024-01-02,B - Medium,Payment Done,Unknown,/eng,Unknown,Unknown,Unknown,...,3.0,83.916667,At Risk,6.431539,51.194169,Germany,Mönchengladbach,North Rhine-Westphalia,360.000000,2520.000000
12339,5805028000023548877,Paula Underwood,2024-01-26,B - Medium,Payment Done,Unknown,eng/digital-marketing,performancemax_digitalmarkt_ru_DE,_{region_name}_,Unknown,...,27.0,670.233333,Stable,13.404954,52.520007,Germany,Berlin,Berlin,1000.000000,7000.000000
12369,5805028000023531229,Ulysses Adams,2024-02-07,A - High,Payment Done,Unknown,/direct,Unknown,Unknown,Unknown,...,40.0,969.883333,Stable,13.404954,52.520007,Germany,Berlin,Berlin,360.000000,2520.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14087,5805028000018767107,Oliver Taylor,2023-12-22,A - High,Payment Done,Unknown,eng/digital-marketing,performancemax_digitalmarkt_ru_DE,_{region_name}_,Unknown,...,25.0,611.833333,At Risk,13.198898,52.635197,Germany,Hennigsdorf,Brandenburg,318.181818,2227.272727
14095,5805028000018700512,Paula Underwood,2024-01-06,C - Low,Payment Done,Unknown,/eng/test,24.09.23retargeting_DE,bloggersvideo5,retargeting,...,41.0,984.966667,Stable,7.588530,50.231200,Germany,Boppard,Rhineland-Palatinate,360.000000,2520.000000
16406,5805028000011754149,Oliver Taylor,NaT,B - Medium,Payment Done,Unknown,/eng/test,performancemax_digitalmarkt_ru_DE,_{region_name}_,Unknown,...,NaN,NaN,At Risk,10.243267,52.320409,Germany,Peine,Lower Saxony,1042.857143,7300.000000
19033,5805028000003553064,Ulysses Adams,2023-08-03,A - High,Payment Done,Unknown,eng/digital-marketing,performancemax_digitalmarkt_ru_DE,_{region_name}_,Unknown,...,1.0,37.116667,Stable,NaN,NaN,None,None,None,320.000000,2240.000000
19391,5805028000002306176,Jane Smith,2023-08-17,B - Medium,Payment Done,Unknown,eng/digital-marketing,12.07.2023wide_DE,v6com,wide,...,28.0,684.083333,Stable,8.726887,52.849472,Germany,Bassum,Lower Saxony,320.000000,2240.000000

In [ ]:
rev_dig_mark = df_dig_mark['R_i'].sum()
rev_ux_ui = df_ux_ui['R_i'].sum()
rev_web_dev = df_web_dev['R_i'].sum()

In [ ]:
aov = revenu / t
aov_dig_mark = rev_dig_mark / t_dig_mark
aov_ux_ui = rev_ux_ui / t_ux_ui
aov_web_dev = rev_web_dev / t_web_dev

In [ ]:
apc = t / b
apc_dig_mark = t_dig_mark / b_dig_mark
apc_ux_ui = t_ux_ui / b_ux_ui
apc_web_dev = t_web_dev / b_web_dev

In [ ]:
cltv = aov * apc
cltv_dig_mark = aov_dig_mark * apc_dig_mark
cltv_ux_ui = aov_ux_ui * apc_ux_ui
cltv_web_dev = aov_web_dev * apc_web_dev

In [ ]:
ltv = (cltv * c1)
ltv_dig_mark =(cltv_dig_mark * c1_dig_mark)
ltv_ux_ui = (cltv_ux_ui * c1_ux_ui)
ltv_web_dev = (cltv_web_dev * c1_web_dev)

In [ ]:
cpa = ac / ua

In [ ]:
cm = ua*(ltv - cpa)
cm_dig_mark = ua*(ltv_dig_mark - cpa)
cm_ux_ui = ua*(ltv_ux_ui - cpa)
cm_web_dev = ua*(ltv_web_dev - cpa)

In [ ]:
def add_row(df, product, **metrics):
    row = {'Product': product}
    row.update(metrics)
    df.loc[len(df)] = row
    return df

In [ ]:
columns = ['Product','UA', 'B', 'C1', 'REV', 'T','AOV', 'APC', 'CLTV', 'LTV', 'AC', 'CPA', 'CM']

In [ ]:
df1 = pd.DataFrame(columns=columns)

In [ ]:
df1 = add_row(df1, 'all', UA=ua, B=b, C1=c1, REV=revenu, T=t, AOV=aov,
              APC=apc, CLTV=cltv, LTV=ltv, AC=ac, CPA=cpa, CM=cm)

df1 = add_row(df1, 'Digital Marketing', UA=ua, B=b_dig_mark, C1=c1_dig_mark,
              T=t_dig_mark, REV=rev_dig_mark, AOV=aov_dig_mark,
              APC=apc_dig_mark, CLTV=cltv_dig_mark, LTV=ltv_dig_mark, AC=ac,
              CPA=cpa, CM=cm_dig_mark)

df1 = add_row(df1, 'UX Design', UA=ua, B=b_ux_ui, C1=c1_ux_ui, T=t_ux_ui,
              REV=rev_ux_ui, AOV=aov_ux_ui, APC=apc_ux_ui, CLTV=cltv_ux_ui,
              LTV=ltv_ux_ui, AC=ac, CPA=cpa, CM=cm_ux_ui)

df1 = add_row(df1, 'Web Developer', UA=ua, B=b_web_dev, C1=c1_web_dev,
              T=t_web_dev, REV=rev_web_dev, AOV=aov_web_dev,
              APC=apc_web_dev, CLTV=cltv_web_dev, LTV=ltv_web_dev, AC=ac,
              CPA=cpa, CM=cm_web_dev)

In [ ]:
df1

,Product,UA,B,C1,REV,T,AOV,APC,CLTV,LTV,AC,CPA,CM
0,all,18510,852,0.046029,3.434095e+06,4550.0,754.746087,5.340376,4030.627579,185.526456,148915.24,8.045124,3.285179e+06
1,Digital Marketing,18510,472,0.025500,2.174668e+06,2890.0,752.480340,6.122881,4607.347843,117.486125,148915.24,8.045124,2.025753e+06
2,UX Design,18510,227,0.012264,9.102632e+05,1161.0,784.033748,5.114537,4009.969964,49.176833,148915.24,8.045124,7.613479e+05
3,Web Developer,18510,136,0.007347,3.491633e+05,499.0,699.726119,3.669118,2567.377451,18.863497,148915.24,8.045124,2.002481e+05

In [ ]:
df1.to_excel('unit.xlsx', index=False)

In [ ]:
df_cont

,Id,Contact Owner Name,Created Time,Modified Time
0,5805028000000645014,Rachel White,2023-06-27 11:28:00,2023-12-22 13:34:00
1,5805028000000872003,Charlie Davis,2023-07-03 11:31:00,2024-05-21 10:23:00
2,5805028000000889001,Bob Brown,2023-07-02 22:37:00,2023-12-21 13:17:00
3,5805028000000907006,Bob Brown,2023-07-03 05:44:00,2023-12-29 15:20:00
4,5805028000000939010,Nina Scott,2023-07-04 10:11:00,2024-04-16 16:14:00
...,...,...,...,...
18543,5805028000056889209,Ulysses Adams,2024-06-21 12:11:00,2024-06-21 14:11:00
18544,5805028000056889351,Eva Kent,2024-06-21 13:32:00,2024-06-21 15:32:00
18545,5805028000056892018,Eva Kent,2024-06-21 10:21:00,2024-06-21 12:21:00
18546,5805028000056892055,Yara Edwards,2024-06-21 10:22:00,2024-06-21 12:23:00
18547,5805028000056907001,Ben Hall,2024-06-21 10:56:00,2024-06-21 12:56:00

In [ ]:
df_cont.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18510 entries, 0 to 18547
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  18510 non-null  object
 1   Contact Owner Name  18510 non-null  object
 2   Created Time        18510 non-null  datetime64[ns]
 3   Modified Time       18510 non-null  datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 723.0+ KB

In [ ]:
ua

18510

In [ ]:
df_cont.describe()

                        Created Time                  Modified Time
count                          18510                          18510
mean   2024-01-24 14:25:56.155591680  2024-02-15 09:11:05.273905920
min              2023-06-27 11:28:00            2023-07-06 10:54:00
25%              2023-11-15 16:49:15            2023-12-09 14:51:45
50%              2024-02-01 18:44:30            2024-02-29 01:12:30
75%              2024-04-12 16:15:45            2024-04-26 22:40:45
max              2024-06-21 15:30:00            2024-06-21 15:32:00

In [ ]:
days = (df_cont['Created Time'].max() - df_cont['Created Time'].min()).days
days

360

 n = 16*p(1-p)/x**2

In [ ]:
print(f'Innerhalb von {days} Tagen wurden {ua} Nutzer registriert, was {round(ua / 52)} pro Woche oder {round(ua / 360)} pro Tag entspricht.')

за 360 дней было зарегистрировано 18510 пользователей, что составляет 356 в неделю или 51 в день

In [ ]:
x1 = 0.03
x2 = 0.03

In [ ]:
p1 = c1_ux_ui
n1 = 16*p1*(1 - p1) / x1**2
print(f'для А/В теста нам понадобится {round(n1)} человек в каждую группу')
t1 = (n1*2 )/ (ua / 365)
print(f'на тест уйдет {round(t1, 1)} дней')

для А/В теста нам понадобится 215 человек в каждую группу
на тест уйдет 8.5 дней

In [ ]:
p2 = c1_web_dev
n2 = 16*p2*(1 - p2) / x2**2
print(f'для А/В теста нам понадобится {round(n2)} человек в каждую группу')
t2 = (n2*2) / (ua / 365)
print(f'на тест уйдет {round(t2, 1)} дней')

для А/В теста нам понадобится 130 человек в каждую группу
на тест уйдет 5.1 дней

In [ ]:
df_deals.columns = df_deals.columns.str.strip().str.replace(' ', '_').str.replace('-', '_')

df_deals.to_csv('deals_t.csv', index=False, encoding='utf-8')

In [ ]:
df_deals.head(1)

In [ ]:
df_deals.to_csv('deals_tb.csv', index=False, sep=';', encoding='utf-8')